  # dynamic groups based on operating systems
- hosts: servers
  tasks:
    - group_by:
        key: os_{{ ansible_distribution }}
    - debug:
        msg: os_{{ ansible_distribution }}

  # Rocky Linux only
- hosts: os_Rocky
  become: true
  vars_files:
    -  "~/.ansible/vault/secrets.yaml"
  vars:
    ansible_become_pass: "{{ rocky_sudo }}"
  tasks:
    - name: dnf upgrade
      dnf:
        name: "*"
        state: latest

  # Archlinux only
- hosts: os_Archlinux
  become: true
  vars_files:
    -  "~/.ansible/vault/secrets.yaml"
  vars:
    ansible_become_pass: "{{ arch_sudo }}"
  tasks:
    - name: pacman -Syu
      pacman:
        update_cache: true
        upgrade: true

